import React, { useState, useEffect } from 'react';
import DetailsPanel from './DetailsPanel';
import AlternativeSprsPanel from './AlternativeSprsPanel';

const exampleRows = [
  {
    Control: '3.1.1',
    Family: 'Access Control',
    Description: 'Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'Access is limited to authorized users, processes, and devices through Azure Active Directory, role-based access control, and Conditional Access policies, ensuring secure system access.',
    Score: -5,
    FAR: 'b.1.i',
    CMMC_L1: 'AC.L1-3.1.1',
    CMMC_L2: 'AC.L1-3.1.1',
  },
  {
    Control: '3.1.2',
    Family: 'Access Control',
    Description: 'Limit system access to the types of transactions and functions that authorized users are permitted to execute.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'We use Microsoft Active Directory and SharePoint Online in the GCC environment to enforce role-based access controls, restricting users to necessary transactions/functions via group memberships, permissions, and conditional rules.',
    Score: -5,
    FAR: 'b.1.ii',
    CMMC_L1: 'AC.L1-3.1.2',
    CMMC_L2: 'AC.L1-3.1.2',
  },
  {
    Control: '3.1.3',
    Family: 'Access Control',
    Description: 'Control the flow of CUI in accordance with approved authorizations.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.3',
  },
  {
    Control: '3.1.4',
    Family: 'Access Control',
    Description: 'Separate the duties of individuals to reduce the risk of malevolent activity without collusion.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.4',
  },
  {
    Control: '3.1.5',
    Family: 'Access Control',
    Description: 'Employ the principle of least privilege, including for specific security functions and privileged accounts.',
    Type: 'Derived',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'Policy maintain a privileged account inventory, restrict access to security functions, and enforce least privilege for authorized users.',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.5',
  },
  {
    Control: '3.1.6',
    Family: 'Access Control',
    Description: 'Use non-privileged accounts or roles when accessing nonsecurity functions.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.6',
  },
  {
    Control: '3.1.7',
    Family: 'Access Control',
    Description: 'Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'In our M365 GCC environment, Active Directory documents privileged functions; Group Policy prevents non-privileged users from executing them, while ThreatLocker Unified Audit logs capture privilege execution per procedures.',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.7',
  },
  {
    Control: '3.1.8',
    Family: 'Access Control',
    Description: 'Limit unsuccessful logon attempts.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.8',
  },
  {
    Control: '3.1.9',
    Family: 'Access Control',
    Description: 'Provide privacy and security notices consistent with applicable CUI rules.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.9',
  },
  {
    Control: '3.1.10',
    Family: 'Access Control',
    Description: 'Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.10',
  },
  {
    Control: '3.1.11',
    Family: 'Access Control',
    Description: 'Terminate (automatically) a user session after a defined condition.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.11',
  },
  {
    Control: '3.1.12*',
    Family: 'Access Control',
    Description: 'Monitor and control remote access sessions.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Do not subtract points if remote access not permitted". Mark as N/A. [See DoD Assessment Methodology for clarification on implementation.]',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.12',
  },
  {
    Control: '3.1.13*',
    Family: 'Access Control',
    Description: 'Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Do not subtract points if remote access not permitted". Mark as N/A.',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.13',
  },
  {
    Control: '3.1.14',
    Family: 'Access Control',
    Description: 'Route remote access via managed access control points.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.14',
  },
  {
    Control: '3.1.15',
    Family: 'Access Control',
    Description: 'Authorize remote execution of privileged commands and remote access to security-relevant information.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.15',
  },
  {
    Control: '3.1.16*',
    Family: 'Access Control',
    Description: 'Authorize wireless access prior to allowing such connections.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Do not subtract points if wireless access not permitted". Mark as N/A. [See DoD Assessment Methodology for clarification on implementation.]',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.16',
  },
  {
    Control: '3.1.17*',
    Family: 'Access Control',
    Description: 'Protect wireless access using authentication and encryption.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Do not subtract points if wireless access not permitted". Mark as N/A.',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.17',
  },
  {
    Control: '3.1.18*',
    Family: 'Access Control',
    Description: 'Limit connection of mobile devices.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Do not subtract points if connection of mobile devices is not permitted". Mark as N/A. [See DoD Assessment Methodology for clarification on implementation.]',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.18',
  },
  {
    Control: '3.1.19*',
    Family: 'Access Control',
    Description: 'Encrypt CUI on mobile devices and mobile computing platforms.',
    Type: 'Derived',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Exposure limited to CUI on mobile platform".',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.19',
  },
  {
    Control: '3.1.20',
    Family: 'Access Control',
    Description: 'Verify and control/limit connections to and use of external systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: 'b.1.iii',
    CMMC_L1: '',
    CMMC_L2: 'AC.L1-3.1.20',
  },
  {
    Control: '3.1.21',
    Family: 'Access Control',
    Description: 'Control use of portable storage devices on external systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.21',
  },
  {
    Control: '3.1.22',
    Family: 'Access Control',
    Description: 'Control CUI posted or processed on publicly accessible systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: 'b.1.iv',
    CMMC_L1: '',
    CMMC_L2: 'AC.L2-3.1.22',
  },
  {
    Control: '3.2.1',
    Family: 'Awareness and Training',
    Description: 'Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AT.L2-3.2.1',
  },
  {
    Control: '3.2.2',
    Family: 'Awareness and Training',
    Description: 'Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AT.L2-3.2.2',
  },
  {
    Control: '3.2.3',
    Family: 'Awareness and Training',
    Description: 'Provide security awareness training on recognizing and reporting potential indicators of insider threat.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AT.L2-3.2.3',
  },
  {
    Control: '3.3.1',
    Family: 'Audit and Accountability',
    Description: 'Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.1',
  },
  {
    Control: '3.3.2',
    Family: 'Audit and Accountability',
    Description: 'Ensure that the actions of individual system users can be uniquely traced to those users, so they can be held accountable for their actions.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.2',
  },
  {
    Control: '3.3.3',
    Family: 'Audit and Accountability',
    Description: 'Review and update logged events.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.3',
  },
  {
    Control: '3.3.4',
    Family: 'Audit and Accountability',
    Description: 'Alert in the event of an audit logging process failure.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.4',
  },
  {
    Control: '3.3.5',
    Family: 'Audit and Accountability',
    Description: 'Correlate audit record review, analysis, and reporting processes for investigation and reporting of unlawful, unauthorized, suspicious, or unusual activity.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.5',
  },
  {
    Control: '3.3.6',
    Family: 'Audit and Accountability',
    Description: 'Provide audit record reduction and report generation to support on-demand analysis and reporting.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.6',
  },
  {
    Control: '3.3.7',
    Family: 'Audit and Accountability',
    Description: 'Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.7',
  },
  {
    Control: '3.3.8',
    Family: 'Audit and Accountability',
    Description: 'Protect audit information and audit logging tools from unauthorized access, modification, and deletion.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.8',
  },
  {
    Control: '3.3.9',
    Family: 'Audit and Accountability',
    Description: 'Limit management of audit logging functionality to a subset of privileged users.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'AU.L2-3.3.9',
  },
  {
    Control: '4.1.1',
    Family: 'Configuration Management',
    Description: 'Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.1',
  },
  {
    Control: '4.1.2',
    Family: 'Configuration Management',
    Description: 'Establish and enforce security configuration settings for information technology products employed in organizational systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.2',
  },
  {
    Control: '4.1.3',
    Family: 'Configuration Management',
    Description: 'Track, review, approve/disapprove, and audit changes to organizational systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.3',
  },
  {
    Control: '4.1.4',
    Family: 'Configuration Management',
    Description: 'Analyze the security impact of changes prior to implementation.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.4',
  },
  {
    Control: '4.1.5',
    Family: 'Configuration Management',
    Description: 'Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.5',
  },
  {
    Control: '4.1.6',
    Family: 'Configuration Management',
    Description: 'Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.6',
  },
  {
    Control: '4.1.7',
    Family: 'Configuration Management',
    Description: 'Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.7',
  },
  {
    Control: '4.1.8',
    Family: 'Configuration Management',
    Description: 'Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.8',
  },
  {
    Control: '4.1.9',
    Family: 'Configuration Management',
    Description: 'Control and monitor user-installed software.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CM.L2-3.4.9',
  },
  {
    Control: '3.5.1',
    Family: 'Identification and Authentication',
    Description: 'Identify system users, processes acting on behalf of users, and devices.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L1-3.5.1',
  },
  {
    Control: '3.5.2',
    Family: 'Identification and Authentication',
    Description: 'Authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L1-3.5.2',
  },
  {
    Control: '3.5.3*',
    Family: 'Identification and Authentication',
    Description: 'Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.',
    Type: 'Derived',
    Weight: 5,
    Partial: 3,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '[Official Partial Credit if Multi-Factor Authentication (MFA) is implemented for Remote and Privileged Users, but not General Users. Not Implemented if MFA is not implemented.]',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.3',
  },
  {
    Control: '3.5.4',
    Family: 'Identification and Authentication',
    Description: 'Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.4',
  },
  {
    Control: '3.5.5',
    Family: 'Identification and Authentication',
    Description: 'Prevent reuse of identifiers for a defined period.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.5',
  },
  {
    Control: '3.5.6',
    Family: 'Identification and Authentication',
    Description: 'Disable identifiers after a defined period of inactivity.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.6',
  },
  {
    Control: '3.5.7',
    Family: 'Identification and Authentication',
    Description: 'Enforce a minimum password complexity and change of characters when new passwords are created.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.7',
  },
  {
    Control: '3.5.8',
    Family: 'Identification and Authentication',
    Description: 'Prohibit password reuse for a specified number of generations.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.8',
  },
  {
    Control: '3.5.9',
    Family: 'Identification and Authentication',
    Description: 'Allow temporary password use for system logons with an immediate change to a permanent password.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.9',
  },
  {
    Control: '3.5.10*',
    Family: 'Identification and Authentication',
    Description: 'Store and transmit only cryptographically-protected passwords.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Encrypted representations of passwords include, for example, encrypted versions of passwords and one-way cryptographic hashes of passwords."',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.10',
  },
  {
    Control: '3.5.11',
    Family: 'Identification and Authentication',
    Description: 'Obscure feedback of authentication information.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IA.L2-3.5.11',
  },
  {
    Control: '3.6.1',
    Family: 'Incident Response',
    Description: 'Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IR.L2-3.6.1',
  },
  {
    Control: '3.6.2',
    Family: 'Incident Response',
    Description: 'Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IR.L2-3.6.2',
  },
  {
    Control: '3.6.3',
    Family: 'Incident Response',
    Description: 'Test the organizational incident response capability.',
    Type: 'Basic',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'IR.L2-3.6.3',
  },
  {
    Control: '3.7.1',
    Family: 'Maintenance',
    Description: 'Perform maintenance on organizational systems.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MA.L2-3.7.1',
  },
  {
    Control: '3.7.2',
    Family: 'Maintenance',
    Description: 'Ensure equipment removed for off-site maintenance is sanitized of any CUI.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MA.L2-3.7.2',
  },
  {
    Control: '3.7.3',
    Family: 'Maintenance',
    Description: 'Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MA.L2-3.7.3',
  },
  {
    Control: '3.7.4',
    Family: 'Maintenance',
    Description: 'Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MA.L2-3.7.4',
  },
  {
    Control: '3.7.5',
    Family: 'Maintenance',
    Description: 'Supervise the maintenance activities of maintenance personnel without required access authorization.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MA.L2-3.7.5',
  },
  {
    Control: '3.7.6',
    Family: 'Maintenance',
    Description: 'Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Exposure limited to CUI on media".',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.1',
  },
  {
    Control: '3.8.2*',
    Family: 'Media Protection',
    Description: 'Limit access to CUI on system media to authorized users.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "Exposure limited to CUI on media".',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.2',
  },
  {
    Control: '3.8.3*',
    Family: 'Media Protection',
    Description: 'Sanitize or destroy system media containing CUI before disposal or release for reuse.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "While exposure limited to CUI on media, failure to sanitize can result in continual exposure of CUI."',
    Score: -5,
    FAR: 'b.1.vii',
    CMMC_L1: 'MP.L1-3.8.3',
    CMMC_L2: 'MP.L1-3.8.3',
  },
  {
    Control: '3.8.4',
    Family: 'Media Protection',
    Description: 'Mark media with necessary CUI markings and distribution limitations.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.4',
  },
  {
    Control: '3.8.5',
    Family: 'Media Protection',
    Description: 'Limit access to media containing CUI and maintain accountability for media during transport outside of controlled areas.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.5',
  },
  {
    Control: '3.8.6',
    Family: 'Media Protection',
    Description: 'Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.6',
  },
  {
    Control: '3.8.7',
    Family: 'Media Protection',
    Description: 'Control the use of removable media on system components.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.7',
  },
  {
    Control: '3.8.8',
    Family: 'Media Protection',
    Description: 'Prohibit the use of portable storage devices when such devices have no identifiable owner.',
    Type: 'Derived',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.8',
  },
  {
    Control: '3.8.9',
    Family: 'Media Protection',
    Description: 'Protect the confidentiality of backup CUI at storage locations.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'MP.L2-3.8.9',
  },
  {
    Control: '3.9.1',
    Family: 'Personnel Security',
    Description: 'Screen individuals prior to authorizing access to organizational systems containing CUI.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'PS.L2-3.9.1',
  },
  {
    Control: '3.9.2',
    Family: 'Personnel Security',
    Description: 'Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'PS.L2-3.9.2',
  },
  {
    Control: '3.10.1',
    Family: 'Physical Protection',
    Description: 'Limit access to organizational systems, equipment, and the respective operating environments to authorized individuals.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: 'b.1.viii',
    CMMC_L1: 'PE.L1-3.10.1',
    CMMC_L2: 'PE.L1-3.10.1',
  },
  {
    Control: '3.10.2',
    Family: 'Physical Protection',
    Description: 'Protect and monitor the physical facility and support infrastructure for organizational systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: 'PE.L2-3.10.2',
    CMMC_L2: 'PE.L2-3.10.2',
  },
  {
    Control: '3.10.3',
    Family: 'Physical Protection',
    Description: 'Escort visitors and monitor visitor activity.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: 'PE.L1-3.10.3',
    CMMC_L2: 'PE.L1-3.10.3',
  },
  {
    Control: '3.10.4',
    Family: 'Physical Protection',
    Description: 'Maintain audit log of physical access.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: 'PE.L1-3.10.4',
    CMMC_L2: 'PE.L1-3.10.4',
  },
  {
    Control: '3.10.5',
    Family: 'Physical Protection',
    Description: 'Control and manage physical access devices.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: 'PE.L1-3.10.5',
    CMMC_L2: 'PE.L1-3.10.5',
  },
  {
    Control: '3.10.6',
    Family: 'Physical Protection',
    Description: 'Enforce safeguarding measures for CUI at alternate work sites.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: 'PE.L2-3.10.6',
    CMMC_L2: 'PE.L2-3.10.6',
  },
  {
    Control: '3.11.1',
    Family: 'Risk Assessment',
    Description: 'Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'RA.L2-3.11.1',
  },
  {
    Control: '3.11.2',
    Family: 'Risk Assessment',
    Description: 'Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'RA.L2-3.11.2',
  },
  {
    Control: '3.11.3',
    Family: 'Risk Assessment',
    Description: 'Remediate vulnerabilities in accordance with risk assessments.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'RA.L2-3.11.3',
  },
  {
    Control: '3.12.1',
    Family: 'Security Assessment',
    Description: 'Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.',
    Type: 'Basic',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CA.L2-3.12.1',
  },
  {
    Control: '3.12.2*',
    Family: 'Security Assessment',
    Description: 'Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "A lack of plan of action for unimplemented security requirements will result in Security Requirement 3.12.2 being marked as Not Implemented."',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CA.L2-3.12.2',
  },
  {
    Control: '3.12.3',
    Family: 'Security Assessment',
    Description: 'Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CA.L2-3.12.3',
  },
  {
    Control: '3.12.4*',
    Family: 'Security Assessment',
    Description: 'Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'DoD AM: "The absence of a system security plan would result in a finding that an assessment could not be completed due to incomplete information and noncompliance with DFARS clause 252.204-7012." [See DoD Assessment Methodology for clarification on implementation.]',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'CA.L2-3.12.4',
  },
  {
    Control: '3.13.1',
    Family: 'System and Communications Protection',
    Description: 'Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: 'SC.L1-3.13.1',
    CMMC_L2: 'SC.L1-3.13.1',
  },
  {
    Control: '3.13.2',
    Family: 'System and Communications Protection',
    Description: 'Apply architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.2',
  },
  {
    Control: '3.13.3',
    Family: 'System and Communications Protection',
    Description: 'Separate user functionality from system management functionality.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.3',
  },
  {
    Control: '3.13.4',
    Family: 'System and Communications Protection',
    Description: 'Prevent unauthorized and unintended information transfer via shared system resources.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.4',
  },
  {
    Control: '3.13.5',
    Family: 'System and Communications Protection',
    Description: 'Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: 'b.1.ix',
    CMMC_L1: 'SC.L1-3.13.5',
    CMMC_L2: 'SC.L1-3.13.5',
  },
  {
    Control: '3.13.6',
    Family: 'System and Communications Protection',
    Description: 'Deny network communications traffic by exception (i.e., deny all, permit by exception).',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.6',
  },
  {
    Control: '3.13.7',
    Family: 'System and Communications Protection',
    Description: 'Prevent remote devices from communicating with organizational systems unless the remote connection is securely established and any remote device connection is terminated when no longer needed.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.7',
  },
  {
    Control: '3.13.8*',
    Family: 'System and Communications Protection',
    Description: 'Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.',
    Type: 'Derived',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'See DoD Assessment Methodology for clarification on implementation.',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.8',
  },
  {
    Control: '3.13.9',
    Family: 'System and Communications Protection',
    Description: 'Terminate network connections associated with communications sessions at the end of the session or after a defined period of inactivity.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.9',
  },
  {
    Control: '3.13.10',
    Family: 'System and Communications Protection',
    Description: 'Establish and manage cryptographic keys for cryptography employed in organizational systems.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.10',
  },
  {
    Control: '3.13.11*',
    Family: 'System and Communications Protection',
    Description: 'Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.',
    Type: 'Derived',
    Weight: 5,
    Partial: 3,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: 'Official Partial Credit if cryptography is employed, but is mostly not FIPS validated. Not Implemented if no cryptography is employed. [See DoD Assessment Methodology for clarification on implementation.]',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.11',
  },
  {
    Control: '3.13.12',
    Family: 'System and Communications Protection',
    Description: 'Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.12',
  },
  {
    Control: '3.13.13',
    Family: 'System and Communications Protection',
    Description: 'Control and monitor the use of mobile code.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.13',
  },
  {
    Control: '3.13.14',
    Family: 'System and Communications Protection',
    Description: 'Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.14',
  },
  {
    Control: '3.13.15',
    Family: 'System and Communications Protection',
    Description: 'Protect the authenticity of communications sessions.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.15',
  },
  {
    Control: '3.13.16',
    Family: 'System and Communications Protection',
    Description: 'Protect the confidentiality of CUI at rest.',
    Type: 'Derived',
    Weight: 1,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -1,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SC.L2-3.13.16',
  },
  {
    Control: '3.14.1',
    Family: 'System and Information Integrity',
    Description: 'Identify, report, and correct system flaws in a timely manner.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: 'b.1.xii',
    CMMC_L1: 'SI.L1-3.14.1',
    CMMC_L2: 'SI.L1-3.14.1',
  },
  {
    Control: '3.14.2',
    Family: 'System and Information Integrity',
    Description: 'Provide protection from malicious code at designated locations within organizational systems.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: 'b.1.xiii',
    CMMC_L1: 'SI.L1-3.14.2',
    CMMC_L2: 'SI.L1-3.14.2',
  },
  {
    Control: '3.14.3',
    Family: 'System and Information Integrity',
    Description: 'Monitor system security alerts and advisories and take action in response.',
    Type: 'Basic',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SI.L2-3.14.3',
  },
  {
    Control: '3.14.4',
    Family: 'System and Information Integrity',
    Description: 'Update malicious code protection mechanisms when new releases are available.',
    Type: 'Derived',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: 'b.1.xiv',
    CMMC_L1: 'SI.L1-3.14.4',
    CMMC_L2: 'SI.L1-3.14.4',
  },
  {
    Control: '3.14.5',
    Family: 'System and Information Integrity',
    Description: 'Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed.',
    Type: 'Basic',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: 'b.1.xv',
    CMMC_L1: 'SI.L1-3.14.5',
    CMMC_L2: 'SI.L1-3.14.5',
  },
  {
    Control: '3.14.6',
    Family: 'System and Information Integrity',
    Description: 'Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks.',
    Type: 'Derived',
    Weight: 5,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -5,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SI.L2-3.14.6',
  },
  {
    Control: '3.14.7',
    Family: 'System and Information Integrity',
    Description: 'Identify unauthorized use of organizational systems.',
    Type: 'Derived',
    Weight: 3,
    Partial: 0,
    Examine: '',
    Interview: '',
    Test: '',
    Status: '',
    POAM: '',
    Notes: '',
    Score: -3,
    FAR: '',
    CMMC_L1: '',
    CMMC_L2: 'SI.L2-3.14.7',
  },
];

const columns = [
  'Control', 'Family', 'Description', 'Type', 'Weight', 'Partial', 'Examine', 'Interview', 'Test', 'Status', 'POAM', 'Notes', 'Score', 'FAR', 'CMMC_L1', 'CMMC_L2'
];

const FieldModal = ({ open, onClose, row, field, onSave }) => {
  const [value, setValue] = useState(row?.[field] || '');

  useEffect(() => {
    setValue(row?.[field] || '');
  }, [row, field]);

  if (!open || !row || !field) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-40">
      <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-md relative">
        <button className="absolute top-2 right-2 text-gray-400 hover:text-gray-700" onClick={onClose}>&times;</button>
        <h2 className="text-lg font-bold mb-2">{field} for {row.Control}</h2>
        <div className="mb-2 text-sm text-gray-700">{row.Description}</div>
        <textarea
          className="w-full border border-gray-300 rounded p-2 mb-4 min-h-[100px]"
          value={value}
          onChange={e => setValue(e.target.value)}
          placeholder={`Enter ${field.toLowerCase()} notes here...`}
        />
        <button
          className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded"
          onClick={() => onSave(value)}
        >
          Save
        </button>
      </div>
    </div>
  );
};

const ChartTable = ({ onSprsScoreChange }) => {
  const [modalOpen, setModalOpen] = useState(false);
  const [modalRow, setModalRow] = useState(null);
  const [modalField, setModalField] = useState(null);
  const [rows, setRows] = useState(exampleRows);

  useEffect(() => {
    // Calculate SPRS score as the sum of all Score values
    const sprsScore = rows.reduce((sum, row) => {
      const val = Number(row.Score);
      return sum + (isNaN(val) ? 0 : val);
    }, 0);
    if (onSprsScoreChange) onSprsScoreChange(sprsScore);
  }, [rows, onSprsScoreChange]);

  const handleFieldClick = (row, field) => {
    setModalRow(row);
    setModalField(field);
    setModalOpen(true);
  };

  const handleModalSave = (value) => {
    setRows(rows.map(r =>
      r === modalRow ? { ...r, [modalField]: value } : r
    ));
    setModalOpen(false);
    setModalRow(null);
    setModalField(null);
  };

  const handleScoreChange = (idx, value) => {
    setRows(rows => rows.map((row, i) =>
      i === idx ? { ...row, Score: value } : row
    ));
  };

  return (
    <>
      <div className="overflow-x-auto bg-white border border-gray-300 rounded-lg shadow mb-8">
        <table className="min-w-full text-xs md:text-sm">
          <thead className="bg-gray-100 sticky top-0 z-10">
            <tr>
              {columns.map((col) => (
                <th key={col} className="px-2 py-2 border-b font-semibold text-left whitespace-nowrap">{col}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, idx) => (
              <tr
                key={idx}
                className={idx % 2 === 0 ? 'bg-white' : 'bg-gray-50'}
              >
                {columns.map((col) => (
                  <td
                    key={col}
                    className={`px-2 py-2 border-b whitespace-pre-line ${col === 'Score' && row.Score < 0 ? 'bg-red-200 text-red-800 font-bold' : ''}`}
                  >
                    {col === 'Score' ? (
                      <input
                        type="number"
                        value={row.Score}
                        onChange={e => handleScoreChange(idx, e.target.value)}
                        className="w-16 border border-gray-300 rounded px-1 py-0.5 text-right bg-white"
                      />
                    ) : (col === 'Examine' || col === 'Interview') ? (
                      <button
                        className="underline text-blue-600 hover:text-blue-800"
                        onClick={() => handleFieldClick(row, col)}
                        type="button"
                      >
                        {row[col] ? 'Edit' : 'Add'}
                      </button>
                    ) : row[col]}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <FieldModal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        row={modalRow}
        field={modalField}
        onSave={handleModalSave}
      />
      <DetailsPanel />
      <AlternativeSprsPanel />
    </>
  );
};

export default ChartTable; 